// packages/web/src/lib/blocks/games/GameList.svelte
<section class="max-w-screen-xl mx-auto p-4">
	<HTag class="h2" {...heading} />

	{#each $page.stuff.games as game}
		<Game {...game} />
	{/each}
</section>

<script>
	import { page } from '$app/stores'
	import HTag from '~/lib/HTag.svelte'
	import Game from './Game.svelte'

	export let heading
</script>

// packages/nextjs/lib/block/game/GameList.jsx
import { useContext } from 'react'
import { GlobalContext } from 'lib/store/Global'
import HTag from 'lib/HTag'
import Game from './Game'

const GameList = ({ heading }) => {
	const { games } = useContext(GlobalContext)

	return (
		<section className="max-w-screen-lg mx-auto p-4">
			<HTag className="h2" {...heading} />

			<div className="grid gap-8">
				{games?.map((game, key) => (
					<Game {...game} key={key} />
				))}
			</div>
		</section>
	)
}

export default GameList
