// packages/web/src/lib/blocks/games/Score.svelte
<div class="{className} flex items-center justify-center gap-2 mx-auto">
	{#if status === 'completed'}
		{$t(site.title.short)}
		<b class="text-[2em]">{total(score)}</b>
		-
		<b class="text-[2em]">{total(score, 1)}</b>
		{opponent.name.short}
	{:else}
		<b class="text-[1.5em]">{$t(site.title.short)}</b>
		vs
		<b class="text-[1.5em]">{opponent.name.short}</b>
	{/if}
</div>

<script>
	import { page } from '$app/stores'
	import { total } from '~/utils/game'
	import { t } from '~/utils/locales'

	export let opponent, status, score, className

	let { site } = $page.stuff
</script>

// packages/nextjs/lib/block/game/Score.jsx
import { useContext } from 'react'
import { GlobalContext } from 'lib/store/Global'
import clsx from 'clsx'
import t from 'utils/locales'
import { total } from 'utils/game'

const Score = ({ opponent, status, score, className }) => {
	const { site } = useContext(GlobalContext)

	return (
		<div className={clsx(className, 'flex items-center justify-center gap-2 mx-auto')}>
			{status === 'completed'
				? <>
					{t(site.title.short)}
					<b className="text-[2em]">{total(score)}</b>
					-
					<b className="text-[2em]">{total(score, 1)}</b>
					{opponent.name.short}
				</> : <>
					<b className="text-[1.5em]">{t(site.title.short)}</b>
					vs
					<b className="text-[1.5em]">{opponent.name.short}</b>
				</>
			}
		</div>
	)
}

export default Score
