// packages/nextjs/lib/block/NewsList.jsx
import css from './NewsList.module.css'
import { useContext } from 'react'
import { GlobalContext } from 'lib/store/Global'
import HTag from 'lib/HTag'
import Link from 'next/link'
import t from 'utils/locale'

const NewsList = ({ heading }) => {
	const { news } = useContext(GlobalContext)

	return (
		<section className="max-w-screen-md mx-auto p-4">
			<HTag className="h2" {...heading} />

			<ul className="bg-white px-4">
				{news?.map(({ date, title, link}, key) => (
					<li className={css.item} key={key}>
						<time
							class="text-j-green-light md:w-[8ch]"
							dateTime={date}
						>
							{date.replace(/-/g, '.')}
						</time>

						{!!link
							? <Link href={link}>{t(title)}</Link>
							: <a>{t(title)}</a>
						}
					</li>
				))}
			</ul>
		</section>
	)
}

export default NewsList

// packages/web/src/lib/blocks/NewsList.svelte
<section class="max-w-screen-md mx-auto p-4">
	<HTag class="h2" {...heading} />

	<ul class="bg-white px-4">
		{#each $page.stuff.news as news}
			<li class="grid gap-x-4 py-2">
				<time class="text-j-green-light md:w-[8ch]" datetime={news.date}>
					{news.date.replace(/-/g, '.')}
				</time>

				<a href={news.link}>
					{$t(news.title)}
				</a>
			</li>
		{/each}
	</ul>
</section>

<style>
	li + li {
		@apply border-t border-ground-light;
	}

	a[href] {
		@apply hover:underline;
	}

	@screen md {
		li {
			grid-template-columns: auto 1fr;
		}
	}
</style>

<script>
	import { t } from '~/utils/locales'
	import { page } from '$app/stores'
	import HTag from '~/lib/HTag.svelte'

	export let heading
</script>
