// packages/nextjs/lib/CTA.jsx
import Link from 'next/link'
import clsx from 'clsx'
import t from 'utils/locales'

const CTA = ({ link, style, className }) => {
	const external = link._type === 'externalLink'
		? { target: '_blank', rel: 'noopener noreferrer' }
		: {}

	return (
		<Link href={link.internalUrl || link.url}>
			<a className={clsx(className, style)} {...external}>
				{t(link.label || link.page.title)}
			</a>
		</Link>
	)
}

export default CTA

// packages/web/src/lib/CTA.svelte
<a {href} class="{className} {style}" {...external}>
	{label}
</a>

<script>
	import { t, t_url } from '~/utils/locales'

	export let link, style, className = ''

	$: href =
		link._type === 'internalLink' ? $t_url(link.internalUrl) :
		link._type === 'externalLink' ? link.url :
		null

	$: label = $t(link.label || link.page.title)

	$: external = link._type === 'externalLink'
		? { target: '_blank', rel: 'noopener noreferrer' }
		: {}
</script>
