// packages/nextjs/lib/block/game/UpcomingGameList.jsx
import css from './UpcomingGameList.module.css'
import { useContext } from 'react'
import { GlobalContext } from 'lib/store/Global'
import HTag from 'lib/HTag'
import Game from './Game'
import CTA from 'lib/CTA'

const UpcomingGameList = ({ heading, cta }) => {
	const { upcomingGames } = useContext(GlobalContext)

	return (
		<section className="max-w-screen-lg mx-auto p-4">
			<HTag className="h2" {...heading} />

			<div className={css.list}>
				{upcomingGames?.map((game, key) => (
					<Game className="first-of-type:j-gradient" {...game} key={key} />
				))}
			</div>

			{!!cta && (
				<p class="text-center mt-8">
					<CTA className="px-4" {...cta} />
				</p>
			)}
		</section>
	)
}

export default UpcomingGameList

// packages/web/src/lib/blocks/games/UpcomingGameList.svelte
<section class="max-w-screen-lg mx-auto p-4">
	<HTag class="h2" {...heading} />

	<div class="list">
		{#each upcomingGames as game}
			<Game {...game} />
		{/each}
	</div>

	{#if cta}
		<p class="text-center mt-8">
			<CTA className="px-4" {...cta} />
		</p>
	{/if}
</section>

<style>
	.list {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
		gap: 1rem;
	}
</style>

<script>
	import { page } from '$app/stores'
	import HTag from '~/lib/HTag.svelte'
	import Game from './Game.svelte'
	import CTA from '~/lib/CTA.svelte'

	export let heading, cta

	let { upcomingGames } = $page.stuff
</script>
