// packages/nextjs/pages/[...slug].jsx
import client from 'utils/sanity'
import groq from 'utils/groq'
import Page from 'lib/Page'

export default ({ page }) => <Page {...page} />

export async function getStaticPaths({ locales }) {
	const paths = await client.fetch(`
		*[_type == 'page' && slug.current != '/'].slug.current
	`)

	return {
		paths: paths
			.map(slug => ({ params: { slug: slug.split('/') } }))
			.flatMap(page => locales.map(locale => ({ ...page, locale }))),
		fallback: false,
	}
}

export async function getStaticProps({ params, locale }) {
	const { slug } = params

	const { page, ...global } = await client.fetch(`
		{
			'page': *[_type == 'page' && slug.current == '${ slug }'][0]{
				...,
				blocks[]{
					...,
					link{ ${groq.internalUrl} },
					cta{ ${groq.cta} }
				}
			},
			${groq.global}
		}
	`)

	return {
		props: {
			locale,
			page,
			global
		}
	}
}

// packages/web/src/routes/[...slug].svelte
<SEO {...page.seo}/>

{#each (page.blocks || []) as block}
	<Block {...block} />
{/each}

<script>
	import SEO from '$lib/SEO.svelte'
	import Block from '$lib/Block.svelte'

	export let page
</script>

<script context="module">
	import client from '$utils/sanity'

	export async function load({ params, url }) {
		const page = await client.fetch(`*[_type == 'page' && slug.current == '${ params.slug || url.pathname }'][0]`)

		if (!!page) {
			return {
				props: {
					page,
				}
			}
		}

		return {
			status: 404,
		}
	}
</script>
