// packages/web/src/routes/[lang]/[...slug].svelte
<SEO {...page.seo}/>

{#each (page.blocks || []) as block (block._key)}
	<Block {...block} />
{/each}

<script>
	import SEO from '~/lib/SEO.svelte'
	import Block from '~/lib/blocks/Block.svelte'

	export let page
</script>

<script context="module">
	import client from '~/utils/sanity'
	import groq from '~/utils/groq'
	import { locales } from '~/utils/locales'

	export async function load({ params }) {
		const { lang, slug } = params

		const page = await client.fetch(`
			*[_type == 'page' && slug.current == '${ slug }'][0]{
				...,
				blocks[]{
					...,
					link{ ${groq.internalUrl} },
					cta{ ${groq.cta} }
				}
			}
		`)

		const accepted_lang = locales.map(l => l.value).includes(lang)

		if (!!accepted_lang && !!page) {
			return {
				props: {
					page,
				}
			}
		}

		return {
			status: 404,
		}
	}
</script>

// packages/nextjs/pages/[...slug].jsx
import client from 'utils/sanity'
import groq from 'utils/groq'
import Page from 'lib/Page'

export default ({ page }) => <Page {...page} />

export async function getStaticPaths({ locales }) {
	const paths = await client.fetch(`
		*[_type == 'page' && slug.current != '/'].slug.current
	`)

	return {
		paths: paths
			.map(slug => ({ params: { slug: slug.split('/') } }))
			.flatMap(page => locales.map(locale => ({ ...page, locale }))),
		fallback: false,
	}
}

export async function getStaticProps({ params, locale }) {
	const { slug } = params

	const { page, ...global } = await client.fetch(`
		{
			'page': *[_type == 'page' && slug.current == '${ slug }'][0]{
				...,
				blocks[]{
					...,
					link{ ${groq.internalUrl} },
					cta{ ${groq.cta} }
				}
			},
			${groq.global}
		}
	`)

	return {
		props: {
			locale,
			page,
			global
		}
	}
}
