// packages/web/src/lib/blocks/roster/Sort.svelte
<button on:click={() => $sort = by}>
	<slot></slot>

	<ChevronUp
		class={$sort === by ? 'text-j-green-light' : 'opacity-10'}
		height="1em"
	/>
</button>

<style>
	button {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 100%;
		font: inherit;
	}
</style>

<script>
	import { sort } from './Roster.svelte'
	import ChevronUp from '~/lib/icons/ChevronUp.svelte'

	export let by
</script>

// packages/nextjs/lib/block/roster/Sort.jsx
import { BiChevronUp, BiChevronDown } from 'react-icons/bi'

const Sort = ({ by, state,  children }) => {
	const [$sort, set$sort] = state

	return (
		<button
			className="flex gap-[0.5ch] items-center justify-center w-full font-inherit"
			onClick={() => set$sort(by)}
		>
			{children}

			{$sort === by
				? <BiChevronUp className="text-j-green-light" />
				: <BiChevronDown className="opacity-10" />
			}


		</button>
	)
}

export default Sort
